// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: meshtastic/deviceonly_legacy.proto

package meshtastic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Legacy NodeInfoLite descriptor used only to decode pre-split
// /prefs/nodes.proto saves during the v24 -> v25 migration boot.
// This preserves the original NodeInfoLite-compatible field numbers needed
// to parse old wire bytes cleanly, including user (2), position (3),
// device_metrics (6), and the legacy-only compatibility fields via_mqtt (8),
// is_favorite (10), and is_ignored (11). Steady-state code does not use
// this struct; it is dropped after migration completes. This file should be
// removed once DEVICESTATE_MIN_VER advances past 24.
type NodeInfoLite_Legacy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint32                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	User          *UserLite              `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Position      *PositionLite          `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Snr           float32                `protobuf:"fixed32,4,opt,name=snr,proto3" json:"snr,omitempty"`
	LastHeard     uint32                 `protobuf:"fixed32,5,opt,name=last_heard,json=lastHeard,proto3" json:"last_heard,omitempty"`
	DeviceMetrics *DeviceMetrics         `protobuf:"bytes,6,opt,name=device_metrics,json=deviceMetrics,proto3" json:"device_metrics,omitempty"`
	Channel       uint32                 `protobuf:"varint,7,opt,name=channel,proto3" json:"channel,omitempty"`
	ViaMqtt       bool                   `protobuf:"varint,8,opt,name=via_mqtt,json=viaMqtt,proto3" json:"via_mqtt,omitempty"`
	HopsAway      *uint32                `protobuf:"varint,9,opt,name=hops_away,json=hopsAway,proto3,oneof" json:"hops_away,omitempty"`
	IsFavorite    bool                   `protobuf:"varint,10,opt,name=is_favorite,json=isFavorite,proto3" json:"is_favorite,omitempty"`
	IsIgnored     bool                   `protobuf:"varint,11,opt,name=is_ignored,json=isIgnored,proto3" json:"is_ignored,omitempty"`
	NextHop       uint32                 `protobuf:"varint,12,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	Bitfield      uint32                 `protobuf:"varint,13,opt,name=bitfield,proto3" json:"bitfield,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoLite_Legacy) Reset() {
	*x = NodeInfoLite_Legacy{}
	mi := &file_meshtastic_deviceonly_legacy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoLite_Legacy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoLite_Legacy) ProtoMessage() {}

func (x *NodeInfoLite_Legacy) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_deviceonly_legacy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoLite_Legacy.ProtoReflect.Descriptor instead.
func (*NodeInfoLite_Legacy) Descriptor() ([]byte, []int) {
	return file_meshtastic_deviceonly_legacy_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfoLite_Legacy) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *NodeInfoLite_Legacy) GetUser() *UserLite {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *NodeInfoLite_Legacy) GetPosition() *PositionLite {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *NodeInfoLite_Legacy) GetSnr() float32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

func (x *NodeInfoLite_Legacy) GetLastHeard() uint32 {
	if x != nil {
		return x.LastHeard
	}
	return 0
}

func (x *NodeInfoLite_Legacy) GetDeviceMetrics() *DeviceMetrics {
	if x != nil {
		return x.DeviceMetrics
	}
	return nil
}

func (x *NodeInfoLite_Legacy) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *NodeInfoLite_Legacy) GetViaMqtt() bool {
	if x != nil {
		return x.ViaMqtt
	}
	return false
}

func (x *NodeInfoLite_Legacy) GetHopsAway() uint32 {
	if x != nil && x.HopsAway != nil {
		return *x.HopsAway
	}
	return 0
}

func (x *NodeInfoLite_Legacy) GetIsFavorite() bool {
	if x != nil {
		return x.IsFavorite
	}
	return false
}

func (x *NodeInfoLite_Legacy) GetIsIgnored() bool {
	if x != nil {
		return x.IsIgnored
	}
	return false
}

func (x *NodeInfoLite_Legacy) GetNextHop() uint32 {
	if x != nil {
		return x.NextHop
	}
	return 0
}

func (x *NodeInfoLite_Legacy) GetBitfield() uint32 {
	if x != nil {
		return x.Bitfield
	}
	return 0
}

// Legacy NodeDatabase shape: one repeated array of fat NodeInfoLite_Legacy
// with no satellite position/telemetry arrays.
type NodeDatabase_Legacy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Nodes         []*NodeInfoLite_Legacy `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeDatabase_Legacy) Reset() {
	*x = NodeDatabase_Legacy{}
	mi := &file_meshtastic_deviceonly_legacy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeDatabase_Legacy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeDatabase_Legacy) ProtoMessage() {}

func (x *NodeDatabase_Legacy) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_deviceonly_legacy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeDatabase_Legacy.ProtoReflect.Descriptor instead.
func (*NodeDatabase_Legacy) Descriptor() ([]byte, []int) {
	return file_meshtastic_deviceonly_legacy_proto_rawDescGZIP(), []int{1}
}

func (x *NodeDatabase_Legacy) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *NodeDatabase_Legacy) GetNodes() []*NodeInfoLite_Legacy {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_meshtastic_deviceonly_legacy_proto protoreflect.FileDescriptor

const file_meshtastic_deviceonly_legacy_proto_rawDesc = "" +
	"\n" +
	"\"meshtastic/deviceonly_legacy.proto\x12\n" +
	"meshtastic\x1a\x1bmeshtastic/deviceonly.proto\x1a\x1ameshtastic/telemetry.proto\x1a\fnanopb.proto\"\xd6\x03\n" +
	"\x13NodeInfoLite_Legacy\x12\x10\n" +
	"\x03num\x18\x01 \x01(\rR\x03num\x12(\n" +
	"\x04user\x18\x02 \x01(\v2\x14.meshtastic.UserLiteR\x04user\x124\n" +
	"\bposition\x18\x03 \x01(\v2\x18.meshtastic.PositionLiteR\bposition\x12\x10\n" +
	"\x03snr\x18\x04 \x01(\x02R\x03snr\x12\x1d\n" +
	"\n" +
	"last_heard\x18\x05 \x01(\aR\tlastHeard\x12@\n" +
	"\x0edevice_metrics\x18\x06 \x01(\v2\x19.meshtastic.DeviceMetricsR\rdeviceMetrics\x12\x18\n" +
	"\achannel\x18\a \x01(\rR\achannel\x12\x19\n" +
	"\bvia_mqtt\x18\b \x01(\bR\aviaMqtt\x12 \n" +
	"\thops_away\x18\t \x01(\rH\x00R\bhopsAway\x88\x01\x01\x12\x1f\n" +
	"\vis_favorite\x18\n" +
	" \x01(\bR\n" +
	"isFavorite\x12\x1d\n" +
	"\n" +
	"is_ignored\x18\v \x01(\bR\tisIgnored\x12\x19\n" +
	"\bnext_hop\x18\f \x01(\rR\anextHop\x12\x1a\n" +
	"\bbitfield\x18\r \x01(\rR\bbitfieldB\f\n" +
	"\n" +
	"_hops_away\"\x99\x01\n" +
	"\x13NodeDatabase_Legacy\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12h\n" +
	"\x05nodes\x18\x02 \x03(\v2\x1f.meshtastic.NodeInfoLite_LegacyB1\x92?.\x92\x01+std::vector<meshtastic_NodeInfoLite_Legacy>R\x05nodesBu\x92?\v\xc2\x01\b<vector>\n" +
	"\x14org.meshtastic.protoB\x10DeviceOnlyLegacyZ#github.com/meshtastic/go/meshtastic\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00b\x06proto3"

var (
	file_meshtastic_deviceonly_legacy_proto_rawDescOnce sync.Once
	file_meshtastic_deviceonly_legacy_proto_rawDescData []byte
)

func file_meshtastic_deviceonly_legacy_proto_rawDescGZIP() []byte {
	file_meshtastic_deviceonly_legacy_proto_rawDescOnce.Do(func() {
		file_meshtastic_deviceonly_legacy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtastic_deviceonly_legacy_proto_rawDesc), len(file_meshtastic_deviceonly_legacy_proto_rawDesc)))
	})
	return file_meshtastic_deviceonly_legacy_proto_rawDescData
}

var file_meshtastic_deviceonly_legacy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meshtastic_deviceonly_legacy_proto_goTypes = []any{
	(*NodeInfoLite_Legacy)(nil), // 0: meshtastic.NodeInfoLite_Legacy
	(*NodeDatabase_Legacy)(nil), // 1: meshtastic.NodeDatabase_Legacy
	(*UserLite)(nil),            // 2: meshtastic.UserLite
	(*PositionLite)(nil),        // 3: meshtastic.PositionLite
	(*DeviceMetrics)(nil),       // 4: meshtastic.DeviceMetrics
}
var file_meshtastic_deviceonly_legacy_proto_depIdxs = []int32{
	2, // 0: meshtastic.NodeInfoLite_Legacy.user:type_name -> meshtastic.UserLite
	3, // 1: meshtastic.NodeInfoLite_Legacy.position:type_name -> meshtastic.PositionLite
	4, // 2: meshtastic.NodeInfoLite_Legacy.device_metrics:type_name -> meshtastic.DeviceMetrics
	0, // 3: meshtastic.NodeDatabase_Legacy.nodes:type_name -> meshtastic.NodeInfoLite_Legacy
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_meshtastic_deviceonly_legacy_proto_init() }
func file_meshtastic_deviceonly_legacy_proto_init() {
	if File_meshtastic_deviceonly_legacy_proto != nil {
		return
	}
	file_meshtastic_deviceonly_proto_init()
	file_meshtastic_telemetry_proto_init()
	file_nanopb_proto_init()
	file_meshtastic_deviceonly_legacy_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtastic_deviceonly_legacy_proto_rawDesc), len(file_meshtastic_deviceonly_legacy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtastic_deviceonly_legacy_proto_goTypes,
		DependencyIndexes: file_meshtastic_deviceonly_legacy_proto_depIdxs,
		MessageInfos:      file_meshtastic_deviceonly_legacy_proto_msgTypes,
	}.Build()
	File_meshtastic_deviceonly_legacy_proto = out.File
	file_meshtastic_deviceonly_legacy_proto_goTypes = nil
	file_meshtastic_deviceonly_legacy_proto_depIdxs = nil
}
