// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: meshtastic/interdevice.proto

package meshtastic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Version of the interdevice protocol spoken on the link. Both sides send
// theirs in the ping/pong handshake; a peer reporting a different one runs
// firmware that does not match and is not talked to.
//
// On a change that breaks the other side (renumbered fields, changed
// semantics, removed messages), raise the value of CURRENT. Do not add
// another entry: this enum carries a single constant, not a history.
type InterdeviceVersion int32

const (
	InterdeviceVersion_INTERDEVICE_VERSION_UNSPECIFIED InterdeviceVersion = 0
	// Never use 1: ping/pong were bools before the handshake existed, and a
	// bool true is the same varint on the wire as the number 1, so firmware
	// predating the handshake would pass it.
	InterdeviceVersion_INTERDEVICE_VERSION_CURRENT InterdeviceVersion = 2
)

// Enum value maps for InterdeviceVersion.
var (
	InterdeviceVersion_name = map[int32]string{
		0: "INTERDEVICE_VERSION_UNSPECIFIED",
		2: "INTERDEVICE_VERSION_CURRENT",
	}
	InterdeviceVersion_value = map[string]int32{
		"INTERDEVICE_VERSION_UNSPECIFIED": 0,
		"INTERDEVICE_VERSION_CURRENT":     2,
	}
)

func (x InterdeviceVersion) Enum() *InterdeviceVersion {
	p := new(InterdeviceVersion)
	*p = x
	return p
}

func (x InterdeviceVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterdeviceVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[0].Descriptor()
}

func (InterdeviceVersion) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[0]
}

func (x InterdeviceVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterdeviceVersion.Descriptor instead.
func (InterdeviceVersion) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{0}
}

// Defines the supported file operations
type FileOperation int32

const (
	FileOperation_GET    FileOperation = 0
	FileOperation_POST   FileOperation = 1
	FileOperation_PUT    FileOperation = 2
	FileOperation_DELETE FileOperation = 3
)

// Enum value maps for FileOperation.
var (
	FileOperation_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "DELETE",
	}
	FileOperation_value = map[string]int32{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"DELETE": 3,
	}
)

func (x FileOperation) Enum() *FileOperation {
	p := new(FileOperation)
	*p = x
	return p
}

func (x FileOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[1].Descriptor()
}

func (FileOperation) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[1]
}

func (x FileOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileOperation.Descriptor instead.
func (FileOperation) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{1}
}

// Outcome of a file or directory operation. The requester must be able to
// tell a transient condition from a definitive one: BUSY is worth another
// try, NOT_FOUND is not.
type FileStatus int32

const (
	FileStatus_FILE_UNSPECIFIED FileStatus = 0
	FileStatus_FILE_OK          FileStatus = 1
	// Retry later: the co-processor is doing card maintenance (mount,
	// free space scan) and cannot serve the request right now
	FileStatus_FILE_BUSY      FileStatus = 2
	FileStatus_FILE_NO_CARD   FileStatus = 3
	FileStatus_FILE_NOT_FOUND FileStatus = 4
	// PUT only: offset did not match the current end of the file. file_size
	// carries the size the file actually has, so the writer can resync (or
	// recognize its own chunk as already written after a lost response).
	FileStatus_FILE_OFFSET_CONFLICT FileStatus = 5
	FileStatus_FILE_IO_ERROR        FileStatus = 6
	FileStatus_FILE_NOT_A_FILE      FileStatus = 7 // path is a directory (GET) or not one (listing)
)

// Enum value maps for FileStatus.
var (
	FileStatus_name = map[int32]string{
		0: "FILE_UNSPECIFIED",
		1: "FILE_OK",
		2: "FILE_BUSY",
		3: "FILE_NO_CARD",
		4: "FILE_NOT_FOUND",
		5: "FILE_OFFSET_CONFLICT",
		6: "FILE_IO_ERROR",
		7: "FILE_NOT_A_FILE",
	}
	FileStatus_value = map[string]int32{
		"FILE_UNSPECIFIED":     0,
		"FILE_OK":              1,
		"FILE_BUSY":            2,
		"FILE_NO_CARD":         3,
		"FILE_NOT_FOUND":       4,
		"FILE_OFFSET_CONFLICT": 5,
		"FILE_IO_ERROR":        6,
		"FILE_NOT_A_FILE":      7,
	}
)

func (x FileStatus) Enum() *FileStatus {
	p := new(FileStatus)
	*p = x
	return p
}

func (x FileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[2].Descriptor()
}

func (FileStatus) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[2]
}

func (x FileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileStatus.Descriptor instead.
func (FileStatus) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{2}
}

// What to do with the SD card of the co-processor
type SdCommand int32

const (
	SdCommand_SD_COMMAND_UNSPECIFIED SdCommand = 0
	SdCommand_SD_MOUNT               SdCommand = 1 // mount a card that is in the slot, also after an eject
	SdCommand_SD_EJECT               SdCommand = 2 // flush and release the card so it can be pulled safely
	SdCommand_SD_FORMAT              SdCommand = 3 // wipe the card and put a fresh FAT on it, then mount it
)

// Enum value maps for SdCommand.
var (
	SdCommand_name = map[int32]string{
		0: "SD_COMMAND_UNSPECIFIED",
		1: "SD_MOUNT",
		2: "SD_EJECT",
		3: "SD_FORMAT",
	}
	SdCommand_value = map[string]int32{
		"SD_COMMAND_UNSPECIFIED": 0,
		"SD_MOUNT":               1,
		"SD_EJECT":               2,
		"SD_FORMAT":              3,
	}
)

func (x SdCommand) Enum() *SdCommand {
	p := new(SdCommand)
	*p = x
	return p
}

func (x SdCommand) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SdCommand) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[3].Descriptor()
}

func (SdCommand) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[3]
}

func (x SdCommand) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SdCommand.Descriptor instead.
func (SdCommand) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{3}
}

type SdCardInfo_CardType int32

const (
	SdCardInfo_NONE         SdCardInfo_CardType = 0
	SdCardInfo_MMC          SdCardInfo_CardType = 1
	SdCardInfo_SD           SdCardInfo_CardType = 2
	SdCardInfo_SDHC         SdCardInfo_CardType = 3
	SdCardInfo_SDXC         SdCardInfo_CardType = 4
	SdCardInfo_UNKNOWN_CARD SdCardInfo_CardType = 5
)

// Enum value maps for SdCardInfo_CardType.
var (
	SdCardInfo_CardType_name = map[int32]string{
		0: "NONE",
		1: "MMC",
		2: "SD",
		3: "SDHC",
		4: "SDXC",
		5: "UNKNOWN_CARD",
	}
	SdCardInfo_CardType_value = map[string]int32{
		"NONE":         0,
		"MMC":          1,
		"SD":           2,
		"SDHC":         3,
		"SDXC":         4,
		"UNKNOWN_CARD": 5,
	}
)

func (x SdCardInfo_CardType) Enum() *SdCardInfo_CardType {
	p := new(SdCardInfo_CardType)
	*p = x
	return p
}

func (x SdCardInfo_CardType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SdCardInfo_CardType) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[4].Descriptor()
}

func (SdCardInfo_CardType) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[4]
}

func (x SdCardInfo_CardType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SdCardInfo_CardType.Descriptor instead.
func (SdCardInfo_CardType) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{3, 0}
}

type SdCardInfo_FatType int32

const (
	SdCardInfo_UNKNOWN_FAT SdCardInfo_FatType = 0
	SdCardInfo_FAT16       SdCardInfo_FatType = 1
	SdCardInfo_FAT32       SdCardInfo_FatType = 2
	SdCardInfo_EXFAT       SdCardInfo_FatType = 3
)

// Enum value maps for SdCardInfo_FatType.
var (
	SdCardInfo_FatType_name = map[int32]string{
		0: "UNKNOWN_FAT",
		1: "FAT16",
		2: "FAT32",
		3: "EXFAT",
	}
	SdCardInfo_FatType_value = map[string]int32{
		"UNKNOWN_FAT": 0,
		"FAT16":       1,
		"FAT32":       2,
		"EXFAT":       3,
	}
)

func (x SdCardInfo_FatType) Enum() *SdCardInfo_FatType {
	p := new(SdCardInfo_FatType)
	*p = x
	return p
}

func (x SdCardInfo_FatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SdCardInfo_FatType) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[5].Descriptor()
}

func (SdCardInfo_FatType) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[5]
}

func (x SdCardInfo_FatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SdCardInfo_FatType.Descriptor instead.
func (SdCardInfo_FatType) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{3, 1}
}

type I2CResult_Status int32

const (
	// Never sent: an all-defaults (e.g. accidentally empty) message must
	// not decode as a successful transaction
	I2CResult_UNSPECIFIED  I2CResult_Status = 0
	I2CResult_OK           I2CResult_Status = 1
	I2CResult_NACK_ADDRESS I2CResult_Status = 2
	I2CResult_NACK_DATA    I2CResult_Status = 3
	I2CResult_ERROR        I2CResult_Status = 4
)

// Enum value maps for I2CResult_Status.
var (
	I2CResult_Status_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "OK",
		2: "NACK_ADDRESS",
		3: "NACK_DATA",
		4: "ERROR",
	}
	I2CResult_Status_value = map[string]int32{
		"UNSPECIFIED":  0,
		"OK":           1,
		"NACK_ADDRESS": 2,
		"NACK_DATA":    3,
		"ERROR":        4,
	}
)

func (x I2CResult_Status) Enum() *I2CResult_Status {
	p := new(I2CResult_Status)
	*p = x
	return p
}

func (x I2CResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (I2CResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_interdevice_proto_enumTypes[6].Descriptor()
}

func (I2CResult_Status) Type() protoreflect.EnumType {
	return &file_meshtastic_interdevice_proto_enumTypes[6]
}

func (x I2CResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use I2CResult_Status.Descriptor instead.
func (I2CResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{4, 0}
}

// Message for file operations
type FileTransfer struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Operation FileOperation          `protobuf:"varint,1,opt,name=operation,proto3,enum=meshtastic.FileOperation" json:"operation,omitempty"` // File operation (GET, POST, PUT, DELETE)
	Filepath  string                 `protobuf:"bytes,2,opt,name=filepath,proto3" json:"filepath,omitempty"`                                  // Path of the file on the SD card
	Filedata  []byte                 `protobuf:"bytes,3,opt,name=filedata,proto3" json:"filedata,omitempty"`                                  // Chunk content (POST/PUT request, GET response)
	Status    FileStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=meshtastic.FileStatus" json:"status,omitempty"`          // Response: outcome of the operation
	Message   string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`                                    // Response: human readable detail, may be empty
	Offset    uint64                 `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`                                     // Byte offset of this chunk within the file (ranged GET/PUT)
	// GET request: number of bytes to read, 0 = max chunk size. A response
	// carries at most the filedata max_size (see interdevice.options) per
	// chunk; larger requests are truncated, visible in the filedata length.
	Length        uint32 `protobuf:"varint,7,opt,name=length,proto3" json:"length,omitempty"`
	FileSize      uint64 `protobuf:"varint,8,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"` // GET response: total size of the file
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransfer) Reset() {
	*x = FileTransfer{}
	mi := &file_meshtastic_interdevice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransfer) ProtoMessage() {}

func (x *FileTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_interdevice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransfer.ProtoReflect.Descriptor instead.
func (*FileTransfer) Descriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{0}
}

func (x *FileTransfer) GetOperation() FileOperation {
	if x != nil {
		return x.Operation
	}
	return FileOperation_GET
}

func (x *FileTransfer) GetFilepath() string {
	if x != nil {
		return x.Filepath
	}
	return ""
}

func (x *FileTransfer) GetFiledata() []byte {
	if x != nil {
		return x.Filedata
	}
	return nil
}

func (x *FileTransfer) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_UNSPECIFIED
}

func (x *FileTransfer) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FileTransfer) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileTransfer) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *FileTransfer) GetFileSize() uint64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

// Message for structured directory listing
type DirectoryListing struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Directory string                 `protobuf:"bytes,1,opt,name=directory,proto3" json:"directory,omitempty"` // Path of the directory
	// One page of entry names, full FAT LFN length. Subdirectories carry a
	// trailing slash. Note that a name whose directory prefix pushes the
	// combined path past the FileTransfer.filepath limit cannot round-trip.
	// Page size is the max_count in interdevice.options; page through with
	// offset and total_count.
	Filenames     []string   `protobuf:"bytes,2,rep,name=filenames,proto3" json:"filenames,omitempty"`
	Status        FileStatus `protobuf:"varint,3,opt,name=status,proto3,enum=meshtastic.FileStatus" json:"status,omitempty"` // Response: outcome of the operation
	Message       string     `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                           // Response: human readable detail, may be empty
	Offset        uint32     `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`                            // Request: skip this many entries (paging)
	TotalCount    uint32     `protobuf:"varint,6,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`  // Response: total number of entries in the directory
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirectoryListing) Reset() {
	*x = DirectoryListing{}
	mi := &file_meshtastic_interdevice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectoryListing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectoryListing) ProtoMessage() {}

func (x *DirectoryListing) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_interdevice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectoryListing.ProtoReflect.Descriptor instead.
func (*DirectoryListing) Descriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{1}
}

func (x *DirectoryListing) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *DirectoryListing) GetFilenames() []string {
	if x != nil {
		return x.Filenames
	}
	return nil
}

func (x *DirectoryListing) GetStatus() FileStatus {
	if x != nil {
		return x.Status
	}
	return FileStatus_FILE_UNSPECIFIED
}

func (x *DirectoryListing) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DirectoryListing) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DirectoryListing) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// A single I2C transaction: an optional write followed by an optional
// read with repeated start, matching the TwoWire usage of sensor drivers
// (beginTransmission/write.../endTransmission(false)/requestFrom)
type I2CTransaction struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Address   uint32                 `protobuf:"varint,1,opt,name=address,proto3" json:"address,omitempty"`                     // 7-bit device address
	WriteData []byte                 `protobuf:"bytes,2,opt,name=write_data,json=writeData,proto3" json:"write_data,omitempty"` // Bytes to write, may be empty
	// Number of bytes to read after the write, 0 = write-only. Bounded by
	// the read_data max_size of I2CResult (see interdevice.options); larger
	// requests are truncated, visible in the returned byte count.
	ReadLen       uint32 `protobuf:"varint,3,opt,name=read_len,json=readLen,proto3" json:"read_len,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I2CTransaction) Reset() {
	*x = I2CTransaction{}
	mi := &file_meshtastic_interdevice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I2CTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I2CTransaction) ProtoMessage() {}

func (x *I2CTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_interdevice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I2CTransaction.ProtoReflect.Descriptor instead.
func (*I2CTransaction) Descriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{2}
}

func (x *I2CTransaction) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

func (x *I2CTransaction) GetWriteData() []byte {
	if x != nil {
		return x.WriteData
	}
	return nil
}

func (x *I2CTransaction) GetReadLen() uint32 {
	if x != nil {
		return x.ReadLen
	}
	return 0
}

// SD card statistics
type SdCardInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Card initialized and usable. False while `busy` is set does not mean
	// there is no card: the co-processor does not know yet.
	Present   bool                `protobuf:"varint,1,opt,name=present,proto3" json:"present,omitempty"`
	CardType  SdCardInfo_CardType `protobuf:"varint,2,opt,name=card_type,json=cardType,proto3,enum=meshtastic.SdCardInfo_CardType" json:"card_type,omitempty"`
	FatType   SdCardInfo_FatType  `protobuf:"varint,3,opt,name=fat_type,json=fatType,proto3,enum=meshtastic.SdCardInfo_FatType" json:"fat_type,omitempty"`
	CardSize  uint64              `protobuf:"varint,4,opt,name=card_size,json=cardSize,proto3" json:"card_size,omitempty"`    // Filesystem size in bytes
	UsedBytes uint64              `protobuf:"varint,5,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"` // Used bytes (may be expensive to compute on FAT32)
	FreeBytes uint64              `protobuf:"varint,6,opt,name=free_bytes,json=freeBytes,proto3" json:"free_bytes,omitempty"` // Free bytes
	// used_bytes/free_bytes are only meaningful when true: the scan behind
	// them runs in the background after mount and can take a while, and a
	// full card is otherwise indistinguishable from a scan in progress
	StatsValid bool `protobuf:"varint,7,opt,name=stats_valid,json=statsValid,proto3" json:"stats_valid,omitempty"`
	// The co-processor is mounting a card right now, so whether one is
	// present is not decided yet. Ask again rather than concluding the slot
	// is empty.
	Busy bool `protobuf:"varint,8,opt,name=busy,proto3" json:"busy,omitempty"`
	// A card answers in the slot but carries no filesystem that could be
	// mounted (present is false then). Formatting it makes it usable.
	Unformatted   bool `protobuf:"varint,9,opt,name=unformatted,proto3" json:"unformatted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SdCardInfo) Reset() {
	*x = SdCardInfo{}
	mi := &file_meshtastic_interdevice_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SdCardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SdCardInfo) ProtoMessage() {}

func (x *SdCardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_interdevice_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SdCardInfo.ProtoReflect.Descriptor instead.
func (*SdCardInfo) Descriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{3}
}

func (x *SdCardInfo) GetPresent() bool {
	if x != nil {
		return x.Present
	}
	return false
}

func (x *SdCardInfo) GetCardType() SdCardInfo_CardType {
	if x != nil {
		return x.CardType
	}
	return SdCardInfo_NONE
}

func (x *SdCardInfo) GetFatType() SdCardInfo_FatType {
	if x != nil {
		return x.FatType
	}
	return SdCardInfo_UNKNOWN_FAT
}

func (x *SdCardInfo) GetCardSize() uint64 {
	if x != nil {
		return x.CardSize
	}
	return 0
}

func (x *SdCardInfo) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *SdCardInfo) GetFreeBytes() uint64 {
	if x != nil {
		return x.FreeBytes
	}
	return 0
}

func (x *SdCardInfo) GetStatsValid() bool {
	if x != nil {
		return x.StatsValid
	}
	return false
}

func (x *SdCardInfo) GetBusy() bool {
	if x != nil {
		return x.Busy
	}
	return false
}

func (x *SdCardInfo) GetUnformatted() bool {
	if x != nil {
		return x.Unformatted
	}
	return false
}

// Result of an I2CTransaction
type I2CResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        I2CResult_Status       `protobuf:"varint,1,opt,name=status,proto3,enum=meshtastic.I2CResult_Status" json:"status,omitempty"`
	ReadData      []byte                 `protobuf:"bytes,2,opt,name=read_data,json=readData,proto3" json:"read_data,omitempty"` // Data read from the device, empty for write-only transactions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I2CResult) Reset() {
	*x = I2CResult{}
	mi := &file_meshtastic_interdevice_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I2CResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I2CResult) ProtoMessage() {}

func (x *I2CResult) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_interdevice_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I2CResult.ProtoReflect.Descriptor instead.
func (*I2CResult) Descriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{4}
}

func (x *I2CResult) GetStatus() I2CResult_Status {
	if x != nil {
		return x.Status
	}
	return I2CResult_UNSPECIFIED
}

func (x *I2CResult) GetReadData() []byte {
	if x != nil {
		return x.ReadData
	}
	return nil
}

// Main message for interdevice communication
type InterdeviceMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Correlates a response with its request: responses echo the id of the
	// request they answer. 0 for unsolicited messages (e.g. the nmea stream).
	Id uint32 `protobuf:"varint,15,opt,name=id,proto3" json:"id,omitempty"`
	// The message data
	//
	// Types that are valid to be assigned to Data:
	//
	//	*InterdeviceMessage_Nmea
	//	*InterdeviceMessage_Beep
	//	*InterdeviceMessage_I2CTransaction
	//	*InterdeviceMessage_I2CResult
	//	*InterdeviceMessage_I2CScan
	//	*InterdeviceMessage_I2CScanResult
	//	*InterdeviceMessage_FileTransfer
	//	*InterdeviceMessage_DirectoryListing
	//	*InterdeviceMessage_GetSdInfo
	//	*InterdeviceMessage_SdInfo_
	//	*InterdeviceMessage_Ping
	//	*InterdeviceMessage_Pong
	//	*InterdeviceMessage_Nack
	//	*InterdeviceMessage_SdCommand
	Data          isInterdeviceMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterdeviceMessage) Reset() {
	*x = InterdeviceMessage{}
	mi := &file_meshtastic_interdevice_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterdeviceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterdeviceMessage) ProtoMessage() {}

func (x *InterdeviceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_interdevice_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterdeviceMessage.ProtoReflect.Descriptor instead.
func (*InterdeviceMessage) Descriptor() ([]byte, []int) {
	return file_meshtastic_interdevice_proto_rawDescGZIP(), []int{5}
}

func (x *InterdeviceMessage) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InterdeviceMessage) GetData() isInterdeviceMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InterdeviceMessage) GetNmea() string {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_Nmea); ok {
			return x.Nmea
		}
	}
	return ""
}

func (x *InterdeviceMessage) GetBeep() uint32 {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_Beep); ok {
			return x.Beep
		}
	}
	return 0
}

func (x *InterdeviceMessage) GetI2CTransaction() *I2CTransaction {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_I2CTransaction); ok {
			return x.I2CTransaction
		}
	}
	return nil
}

func (x *InterdeviceMessage) GetI2CResult() *I2CResult {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_I2CResult); ok {
			return x.I2CResult
		}
	}
	return nil
}

func (x *InterdeviceMessage) GetI2CScan() bool {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_I2CScan); ok {
			return x.I2CScan
		}
	}
	return false
}

func (x *InterdeviceMessage) GetI2CScanResult() []byte {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_I2CScanResult); ok {
			return x.I2CScanResult
		}
	}
	return nil
}

func (x *InterdeviceMessage) GetFileTransfer() *FileTransfer {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_FileTransfer); ok {
			return x.FileTransfer
		}
	}
	return nil
}

func (x *InterdeviceMessage) GetDirectoryListing() *DirectoryListing {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_DirectoryListing); ok {
			return x.DirectoryListing
		}
	}
	return nil
}

func (x *InterdeviceMessage) GetGetSdInfo() bool {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_GetSdInfo); ok {
			return x.GetSdInfo
		}
	}
	return false
}

func (x *InterdeviceMessage) GetSdInfo_() *SdCardInfo {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_SdInfo_); ok {
			return x.SdInfo_
		}
	}
	return nil
}

func (x *InterdeviceMessage) GetPing() InterdeviceVersion {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_Ping); ok {
			return x.Ping
		}
	}
	return InterdeviceVersion_INTERDEVICE_VERSION_UNSPECIFIED
}

func (x *InterdeviceMessage) GetPong() InterdeviceVersion {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_Pong); ok {
			return x.Pong
		}
	}
	return InterdeviceVersion_INTERDEVICE_VERSION_UNSPECIFIED
}

func (x *InterdeviceMessage) GetNack() bool {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_Nack); ok {
			return x.Nack
		}
	}
	return false
}

func (x *InterdeviceMessage) GetSdCommand() SdCommand {
	if x != nil {
		if x, ok := x.Data.(*InterdeviceMessage_SdCommand); ok {
			return x.SdCommand
		}
	}
	return SdCommand_SD_COMMAND_UNSPECIFIED
}

type isInterdeviceMessage_Data interface {
	isInterdeviceMessage_Data()
}

type InterdeviceMessage_Nmea struct {
	Nmea string `protobuf:"bytes,1,opt,name=nmea,proto3,oneof"`
}

type InterdeviceMessage_Beep struct {
	Beep uint32 `protobuf:"varint,2,opt,name=beep,proto3,oneof"`
}

type InterdeviceMessage_I2CTransaction struct {
	I2CTransaction *I2CTransaction `protobuf:"bytes,3,opt,name=i2c_transaction,json=i2cTransaction,proto3,oneof"`
}

type InterdeviceMessage_I2CResult struct {
	I2CResult *I2CResult `protobuf:"bytes,4,opt,name=i2c_result,json=i2cResult,proto3,oneof"`
}

type InterdeviceMessage_I2CScan struct {
	I2CScan bool `protobuf:"varint,5,opt,name=i2c_scan,json=i2cScan,proto3,oneof"` // Request: scan the secondary I2C bus
}

type InterdeviceMessage_I2CScanResult struct {
	I2CScanResult []byte `protobuf:"bytes,6,opt,name=i2c_scan_result,json=i2cScanResult,proto3,oneof"` // Response: 7-bit addresses of discovered devices
}

type InterdeviceMessage_FileTransfer struct {
	FileTransfer *FileTransfer `protobuf:"bytes,7,opt,name=file_transfer,json=fileTransfer,proto3,oneof"`
}

type InterdeviceMessage_DirectoryListing struct {
	DirectoryListing *DirectoryListing `protobuf:"bytes,8,opt,name=directory_listing,json=directoryListing,proto3,oneof"`
}

type InterdeviceMessage_GetSdInfo struct {
	GetSdInfo bool `protobuf:"varint,9,opt,name=get_sd_info,json=getSdInfo,proto3,oneof"` // Request: SD card statistics
}

type InterdeviceMessage_SdInfo_ struct {
	SdInfo_ *SdCardInfo `protobuf:"bytes,10,opt,name=sd_info,json=sdInfo,proto3,oneof"` // Response
}

type InterdeviceMessage_Ping struct {
	// Link liveness probe and version handshake. The receiver answers ping
	// with pong, echoing the id. Touches no peripherals, so it works with
	// nothing attached. Both carry the version the sender speaks; a peer
	// that answers with a different one speaks another protocol and must
	// not be used.
	Ping InterdeviceVersion `protobuf:"varint,11,opt,name=ping,proto3,enum=meshtastic.InterdeviceVersion,oneof"`
}

type InterdeviceMessage_Pong struct {
	Pong InterdeviceVersion `protobuf:"varint,12,opt,name=pong,proto3,enum=meshtastic.InterdeviceVersion,oneof"`
}

type InterdeviceMessage_Nack struct {
	// Response: the request could not be decoded or is of an unhandled
	// type, so the requester fails fast instead of burning its timeout.
	// Echoes the id when known, 0 when the frame was undecodable. Never
	// sent in reaction to a nack.
	Nack bool `protobuf:"varint,13,opt,name=nack,proto3,oneof"`
}

type InterdeviceMessage_SdCommand struct {
	// Request: mount the card, or release it so it can be pulled safely. The
	// co-processor answers with sd_info. Without an eject the card is mounted
	// on its own and kept mounted; after one it stays released until a mount
	// is asked for.
	SdCommand SdCommand `protobuf:"varint,14,opt,name=sd_command,json=sdCommand,proto3,enum=meshtastic.SdCommand,oneof"`
}

func (*InterdeviceMessage_Nmea) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_Beep) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_I2CTransaction) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_I2CResult) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_I2CScan) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_I2CScanResult) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_FileTransfer) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_DirectoryListing) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_GetSdInfo) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_SdInfo_) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_Ping) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_Pong) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_Nack) isInterdeviceMessage_Data() {}

func (*InterdeviceMessage_SdCommand) isInterdeviceMessage_Data() {}

var File_meshtastic_interdevice_proto protoreflect.FileDescriptor

const file_meshtastic_interdevice_proto_rawDesc = "" +
	"\n" +
	"\x1cmeshtastic/interdevice.proto\x12\n" +
	"meshtastic\"\x96\x02\n" +
	"\fFileTransfer\x127\n" +
	"\toperation\x18\x01 \x01(\x0e2\x19.meshtastic.FileOperationR\toperation\x12\x1a\n" +
	"\bfilepath\x18\x02 \x01(\tR\bfilepath\x12\x1a\n" +
	"\bfiledata\x18\x03 \x01(\fR\bfiledata\x12.\n" +
	"\x06status\x18\x04 \x01(\x0e2\x16.meshtastic.FileStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\a \x01(\rR\x06length\x12\x1b\n" +
	"\tfile_size\x18\b \x01(\x04R\bfileSize\"\xd1\x01\n" +
	"\x10DirectoryListing\x12\x1c\n" +
	"\tdirectory\x18\x01 \x01(\tR\tdirectory\x12\x1c\n" +
	"\tfilenames\x18\x02 \x03(\tR\tfilenames\x12.\n" +
	"\x06status\x18\x03 \x01(\x0e2\x16.meshtastic.FileStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\rR\x06offset\x12\x1f\n" +
	"\vtotal_count\x18\x06 \x01(\rR\n" +
	"totalCount\"d\n" +
	"\x0eI2CTransaction\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\rR\aaddress\x12\x1d\n" +
	"\n" +
	"write_data\x18\x02 \x01(\fR\twriteData\x12\x19\n" +
	"\bread_len\x18\x03 \x01(\rR\areadLen\"\xdb\x03\n" +
	"\n" +
	"SdCardInfo\x12\x18\n" +
	"\apresent\x18\x01 \x01(\bR\apresent\x12<\n" +
	"\tcard_type\x18\x02 \x01(\x0e2\x1f.meshtastic.SdCardInfo.CardTypeR\bcardType\x129\n" +
	"\bfat_type\x18\x03 \x01(\x0e2\x1e.meshtastic.SdCardInfo.FatTypeR\afatType\x12\x1b\n" +
	"\tcard_size\x18\x04 \x01(\x04R\bcardSize\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x05 \x01(\x04R\tusedBytes\x12\x1d\n" +
	"\n" +
	"free_bytes\x18\x06 \x01(\x04R\tfreeBytes\x12\x1f\n" +
	"\vstats_valid\x18\a \x01(\bR\n" +
	"statsValid\x12\x12\n" +
	"\x04busy\x18\b \x01(\bR\x04busy\x12 \n" +
	"\vunformatted\x18\t \x01(\bR\vunformatted\"K\n" +
	"\bCardType\x12\b\n" +
	"\x04NONE\x10\x00\x12\a\n" +
	"\x03MMC\x10\x01\x12\x06\n" +
	"\x02SD\x10\x02\x12\b\n" +
	"\x04SDHC\x10\x03\x12\b\n" +
	"\x04SDXC\x10\x04\x12\x10\n" +
	"\fUNKNOWN_CARD\x10\x05\";\n" +
	"\aFatType\x12\x0f\n" +
	"\vUNKNOWN_FAT\x10\x00\x12\t\n" +
	"\x05FAT16\x10\x01\x12\t\n" +
	"\x05FAT32\x10\x02\x12\t\n" +
	"\x05EXFAT\x10\x03\"\xad\x01\n" +
	"\tI2CResult\x124\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1c.meshtastic.I2CResult.StatusR\x06status\x12\x1b\n" +
	"\tread_data\x18\x02 \x01(\fR\breadData\"M\n" +
	"\x06Status\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x10\n" +
	"\fNACK_ADDRESS\x10\x02\x12\r\n" +
	"\tNACK_DATA\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\"\xbb\x05\n" +
	"\x12InterdeviceMessage\x12\x0e\n" +
	"\x02id\x18\x0f \x01(\rR\x02id\x12\x14\n" +
	"\x04nmea\x18\x01 \x01(\tH\x00R\x04nmea\x12\x14\n" +
	"\x04beep\x18\x02 \x01(\rH\x00R\x04beep\x12E\n" +
	"\x0fi2c_transaction\x18\x03 \x01(\v2\x1a.meshtastic.I2CTransactionH\x00R\x0ei2cTransaction\x126\n" +
	"\n" +
	"i2c_result\x18\x04 \x01(\v2\x15.meshtastic.I2CResultH\x00R\ti2cResult\x12\x1b\n" +
	"\bi2c_scan\x18\x05 \x01(\bH\x00R\ai2cScan\x12(\n" +
	"\x0fi2c_scan_result\x18\x06 \x01(\fH\x00R\ri2cScanResult\x12?\n" +
	"\rfile_transfer\x18\a \x01(\v2\x18.meshtastic.FileTransferH\x00R\ffileTransfer\x12K\n" +
	"\x11directory_listing\x18\b \x01(\v2\x1c.meshtastic.DirectoryListingH\x00R\x10directoryListing\x12 \n" +
	"\vget_sd_info\x18\t \x01(\bH\x00R\tgetSdInfo\x121\n" +
	"\asd_info\x18\n" +
	" \x01(\v2\x16.meshtastic.SdCardInfoH\x00R\x06sdInfo\x124\n" +
	"\x04ping\x18\v \x01(\x0e2\x1e.meshtastic.InterdeviceVersionH\x00R\x04ping\x124\n" +
	"\x04pong\x18\f \x01(\x0e2\x1e.meshtastic.InterdeviceVersionH\x00R\x04pong\x12\x14\n" +
	"\x04nack\x18\r \x01(\bH\x00R\x04nack\x126\n" +
	"\n" +
	"sd_command\x18\x0e \x01(\x0e2\x15.meshtastic.SdCommandH\x00R\tsdCommandB\x06\n" +
	"\x04data*Z\n" +
	"\x12InterdeviceVersion\x12#\n" +
	"\x1fINTERDEVICE_VERSION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bINTERDEVICE_VERSION_CURRENT\x10\x02*7\n" +
	"\rFileOperation\x12\a\n" +
	"\x03GET\x10\x00\x12\b\n" +
	"\x04POST\x10\x01\x12\a\n" +
	"\x03PUT\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03*\xa6\x01\n" +
	"\n" +
	"FileStatus\x12\x14\n" +
	"\x10FILE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aFILE_OK\x10\x01\x12\r\n" +
	"\tFILE_BUSY\x10\x02\x12\x10\n" +
	"\fFILE_NO_CARD\x10\x03\x12\x12\n" +
	"\x0eFILE_NOT_FOUND\x10\x04\x12\x18\n" +
	"\x14FILE_OFFSET_CONFLICT\x10\x05\x12\x11\n" +
	"\rFILE_IO_ERROR\x10\x06\x12\x13\n" +
	"\x0fFILE_NOT_A_FILE\x10\a*R\n" +
	"\tSdCommand\x12\x1a\n" +
	"\x16SD_COMMAND_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bSD_MOUNT\x10\x01\x12\f\n" +
	"\bSD_EJECT\x10\x02\x12\r\n" +
	"\tSD_FORMAT\x10\x03Bh\n" +
	"\x14org.meshtastic.protoB\x11InterdeviceProtosZ#github.com/meshtastic/go/meshtastic\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00b\x06proto3"

var (
	file_meshtastic_interdevice_proto_rawDescOnce sync.Once
	file_meshtastic_interdevice_proto_rawDescData []byte
)

func file_meshtastic_interdevice_proto_rawDescGZIP() []byte {
	file_meshtastic_interdevice_proto_rawDescOnce.Do(func() {
		file_meshtastic_interdevice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtastic_interdevice_proto_rawDesc), len(file_meshtastic_interdevice_proto_rawDesc)))
	})
	return file_meshtastic_interdevice_proto_rawDescData
}

var file_meshtastic_interdevice_proto_enumTypes = make([]protoimpl.EnumInfo, 7)
var file_meshtastic_interdevice_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_meshtastic_interdevice_proto_goTypes = []any{
	(InterdeviceVersion)(0),    // 0: meshtastic.InterdeviceVersion
	(FileOperation)(0),         // 1: meshtastic.FileOperation
	(FileStatus)(0),            // 2: meshtastic.FileStatus
	(SdCommand)(0),             // 3: meshtastic.SdCommand
	(SdCardInfo_CardType)(0),   // 4: meshtastic.SdCardInfo.CardType
	(SdCardInfo_FatType)(0),    // 5: meshtastic.SdCardInfo.FatType
	(I2CResult_Status)(0),      // 6: meshtastic.I2CResult.Status
	(*FileTransfer)(nil),       // 7: meshtastic.FileTransfer
	(*DirectoryListing)(nil),   // 8: meshtastic.DirectoryListing
	(*I2CTransaction)(nil),     // 9: meshtastic.I2CTransaction
	(*SdCardInfo)(nil),         // 10: meshtastic.SdCardInfo
	(*I2CResult)(nil),          // 11: meshtastic.I2CResult
	(*InterdeviceMessage)(nil), // 12: meshtastic.InterdeviceMessage
}
var file_meshtastic_interdevice_proto_depIdxs = []int32{
	1,  // 0: meshtastic.FileTransfer.operation:type_name -> meshtastic.FileOperation
	2,  // 1: meshtastic.FileTransfer.status:type_name -> meshtastic.FileStatus
	2,  // 2: meshtastic.DirectoryListing.status:type_name -> meshtastic.FileStatus
	4,  // 3: meshtastic.SdCardInfo.card_type:type_name -> meshtastic.SdCardInfo.CardType
	5,  // 4: meshtastic.SdCardInfo.fat_type:type_name -> meshtastic.SdCardInfo.FatType
	6,  // 5: meshtastic.I2CResult.status:type_name -> meshtastic.I2CResult.Status
	9,  // 6: meshtastic.InterdeviceMessage.i2c_transaction:type_name -> meshtastic.I2CTransaction
	11, // 7: meshtastic.InterdeviceMessage.i2c_result:type_name -> meshtastic.I2CResult
	7,  // 8: meshtastic.InterdeviceMessage.file_transfer:type_name -> meshtastic.FileTransfer
	8,  // 9: meshtastic.InterdeviceMessage.directory_listing:type_name -> meshtastic.DirectoryListing
	10, // 10: meshtastic.InterdeviceMessage.sd_info:type_name -> meshtastic.SdCardInfo
	0,  // 11: meshtastic.InterdeviceMessage.ping:type_name -> meshtastic.InterdeviceVersion
	0,  // 12: meshtastic.InterdeviceMessage.pong:type_name -> meshtastic.InterdeviceVersion
	3,  // 13: meshtastic.InterdeviceMessage.sd_command:type_name -> meshtastic.SdCommand
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_meshtastic_interdevice_proto_init() }
func file_meshtastic_interdevice_proto_init() {
	if File_meshtastic_interdevice_proto != nil {
		return
	}
	file_meshtastic_interdevice_proto_msgTypes[5].OneofWrappers = []any{
		(*InterdeviceMessage_Nmea)(nil),
		(*InterdeviceMessage_Beep)(nil),
		(*InterdeviceMessage_I2CTransaction)(nil),
		(*InterdeviceMessage_I2CResult)(nil),
		(*InterdeviceMessage_I2CScan)(nil),
		(*InterdeviceMessage_I2CScanResult)(nil),
		(*InterdeviceMessage_FileTransfer)(nil),
		(*InterdeviceMessage_DirectoryListing)(nil),
		(*InterdeviceMessage_GetSdInfo)(nil),
		(*InterdeviceMessage_SdInfo_)(nil),
		(*InterdeviceMessage_Ping)(nil),
		(*InterdeviceMessage_Pong)(nil),
		(*InterdeviceMessage_Nack)(nil),
		(*InterdeviceMessage_SdCommand)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtastic_interdevice_proto_rawDesc), len(file_meshtastic_interdevice_proto_rawDesc)),
			NumEnums:      7,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtastic_interdevice_proto_goTypes,
		DependencyIndexes: file_meshtastic_interdevice_proto_depIdxs,
		EnumInfos:         file_meshtastic_interdevice_proto_enumTypes,
		MessageInfos:      file_meshtastic_interdevice_proto_msgTypes,
	}.Build()
	File_meshtastic_interdevice_proto = out.File
	file_meshtastic_interdevice_proto_goTypes = nil
	file_meshtastic_interdevice_proto_depIdxs = nil
}
