// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: meshtastic/lorawan_bridge.proto

package meshtastic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Values 0 to 7 mirror the Semtech TX_ACK error field. Keep every value non
// negative; enums encode as int32.
type LoRaWANBridge_TxResult_Status int32

const (
	LoRaWANBridge_TxResult_NONE             LoRaWANBridge_TxResult_Status = 0
	LoRaWANBridge_TxResult_TOO_LATE         LoRaWANBridge_TxResult_Status = 1
	LoRaWANBridge_TxResult_TOO_EARLY        LoRaWANBridge_TxResult_Status = 2
	LoRaWANBridge_TxResult_COLLISION_PACKET LoRaWANBridge_TxResult_Status = 3
	LoRaWANBridge_TxResult_COLLISION_BEACON LoRaWANBridge_TxResult_Status = 4
	LoRaWANBridge_TxResult_TX_FREQ          LoRaWANBridge_TxResult_Status = 5
	LoRaWANBridge_TxResult_TX_POWER         LoRaWANBridge_TxResult_Status = 6
	LoRaWANBridge_TxResult_GPS_UNLOCKED     LoRaWANBridge_TxResult_Status = 7
	// Held by the gateway for a later receive window.
	LoRaWANBridge_TxResult_DEFERRED LoRaWANBridge_TxResult_Status = 8
	// Discarded, either undeferrable or refused by an authorization check.
	LoRaWANBridge_TxResult_DROPPED LoRaWANBridge_TxResult_Status = 9
)

// Enum value maps for LoRaWANBridge_TxResult_Status.
var (
	LoRaWANBridge_TxResult_Status_name = map[int32]string{
		0: "NONE",
		1: "TOO_LATE",
		2: "TOO_EARLY",
		3: "COLLISION_PACKET",
		4: "COLLISION_BEACON",
		5: "TX_FREQ",
		6: "TX_POWER",
		7: "GPS_UNLOCKED",
		8: "DEFERRED",
		9: "DROPPED",
	}
	LoRaWANBridge_TxResult_Status_value = map[string]int32{
		"NONE":             0,
		"TOO_LATE":         1,
		"TOO_EARLY":        2,
		"COLLISION_PACKET": 3,
		"COLLISION_BEACON": 4,
		"TX_FREQ":          5,
		"TX_POWER":         6,
		"GPS_UNLOCKED":     7,
		"DEFERRED":         8,
		"DROPPED":          9,
	}
)

func (x LoRaWANBridge_TxResult_Status) Enum() *LoRaWANBridge_TxResult_Status {
	p := new(LoRaWANBridge_TxResult_Status)
	*p = x
	return p
}

func (x LoRaWANBridge_TxResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoRaWANBridge_TxResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_meshtastic_lorawan_bridge_proto_enumTypes[0].Descriptor()
}

func (LoRaWANBridge_TxResult_Status) Type() protoreflect.EnumType {
	return &file_meshtastic_lorawan_bridge_proto_enumTypes[0]
}

func (x LoRaWANBridge_TxResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoRaWANBridge_TxResult_Status.Descriptor instead.
func (LoRaWANBridge_TxResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_meshtastic_lorawan_bridge_proto_rawDescGZIP(), []int{0, 3, 0}
}

// Payload for LORAWAN_BRIDGE packets. Tunnels raw LoRaWAN PHY payloads and their
// RF metadata so a gateway can reach a network server over a mesh.
type LoRaWANBridge struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Variant:
	//
	//	*LoRaWANBridge_Uplink_
	//	*LoRaWANBridge_Downlink_
	//	*LoRaWANBridge_TxResult_
	//	*LoRaWANBridge_Chunk
	Variant       isLoRaWANBridge_Variant `protobuf_oneof:"variant"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoRaWANBridge) Reset() {
	*x = LoRaWANBridge{}
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoRaWANBridge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoRaWANBridge) ProtoMessage() {}

func (x *LoRaWANBridge) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoRaWANBridge.ProtoReflect.Descriptor instead.
func (*LoRaWANBridge) Descriptor() ([]byte, []int) {
	return file_meshtastic_lorawan_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *LoRaWANBridge) GetVariant() isLoRaWANBridge_Variant {
	if x != nil {
		return x.Variant
	}
	return nil
}

func (x *LoRaWANBridge) GetUplink() *LoRaWANBridge_Uplink {
	if x != nil {
		if x, ok := x.Variant.(*LoRaWANBridge_Uplink_); ok {
			return x.Uplink
		}
	}
	return nil
}

func (x *LoRaWANBridge) GetDownlink() *LoRaWANBridge_Downlink {
	if x != nil {
		if x, ok := x.Variant.(*LoRaWANBridge_Downlink_); ok {
			return x.Downlink
		}
	}
	return nil
}

func (x *LoRaWANBridge) GetTxResult() *LoRaWANBridge_TxResult {
	if x != nil {
		if x, ok := x.Variant.(*LoRaWANBridge_TxResult_); ok {
			return x.TxResult
		}
	}
	return nil
}

func (x *LoRaWANBridge) GetChunk() *LoRaWANBridge_PayloadChunk {
	if x != nil {
		if x, ok := x.Variant.(*LoRaWANBridge_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isLoRaWANBridge_Variant interface {
	isLoRaWANBridge_Variant()
}

type LoRaWANBridge_Uplink_ struct {
	Uplink *LoRaWANBridge_Uplink `protobuf:"bytes,1,opt,name=uplink,proto3,oneof"`
}

type LoRaWANBridge_Downlink_ struct {
	Downlink *LoRaWANBridge_Downlink `protobuf:"bytes,2,opt,name=downlink,proto3,oneof"`
}

type LoRaWANBridge_TxResult_ struct {
	TxResult *LoRaWANBridge_TxResult `protobuf:"bytes,3,opt,name=tx_result,json=txResult,proto3,oneof"`
}

type LoRaWANBridge_Chunk struct {
	Chunk *LoRaWANBridge_PayloadChunk `protobuf:"bytes,4,opt,name=chunk,proto3,oneof"`
}

func (*LoRaWANBridge_Uplink_) isLoRaWANBridge_Variant() {}

func (*LoRaWANBridge_Downlink_) isLoRaWANBridge_Variant() {}

func (*LoRaWANBridge_TxResult_) isLoRaWANBridge_Variant() {}

func (*LoRaWANBridge_Chunk) isLoRaWANBridge_Variant() {}

// An uplink heard by the gateway, travelling towards the network server.
type LoRaWANBridge_Uplink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Receive frequency in Hz.
	FreqHz uint32 `protobuf:"fixed32,1,opt,name=freq_hz,json=freqHz,proto3" json:"freq_hz,omitempty"`
	// Concentrator receive timestamp in microseconds. Free running, wraps about
	// every 72 minutes.
	Tmst uint32 `protobuf:"fixed32,2,opt,name=tmst,proto3" json:"tmst,omitempty"`
	// Received signal strength in tenths of a dBm. Fits signed 16 bit.
	RssiX10 int32 `protobuf:"zigzag32,3,opt,name=rssi_x10,json=rssiX10,proto3" json:"rssi_x10,omitempty"`
	// Signal to noise ratio in tenths of a dB. Fits signed 16 bit.
	SnrX10 int32 `protobuf:"zigzag32,4,opt,name=snr_x10,json=snrX10,proto3" json:"snr_x10,omitempty"`
	// Packed radio settings, 0 to 255. Meaningless when fsk_bitrate is set.
	//
	//	bits 7-5  0 to 7 for SF5 to SF12
	//	bits 4-2  bandwidth in kHz: 0 125, 1 250, 2 500, 3 203.125, 4 406.25,
	//	          5 812.5, 6 1625, 7 reserved. Codes 0 to 2 are the sub-GHz set
	//	          and 3 to 6 the 2.4 GHz set; the two do not overlap. Any future
	//	          bandwidth takes the next free code rather than sorting in.
	//	bits 1-0  0 to 3 for 4/5 to 4/8
	RadioParams uint32 `protobuf:"varint,5,opt,name=radio_params,json=radioParams,proto3" json:"radio_params,omitempty"`
	// FSK bit rate in bits per second. Non-zero only for an FSK frame, in which
	// case radio_params does not apply. Fits unsigned 16 bit.
	FskBitrate uint32 `protobuf:"varint,9,opt,name=fsk_bitrate,json=fskBitrate,proto3" json:"fsk_bitrate,omitempty"`
	// PHY payload, or its first part when chunk_count is 2.
	Payload []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	// Groups this head with its continuation. 1 to 255, or 0 when not chunked.
	PayloadId uint32 `protobuf:"varint,7,opt,name=payload_id,json=payloadId,proto3" json:"payload_id,omitempty"`
	// 0 when the frame fits one packet, otherwise 2.
	ChunkCount    uint32 `protobuf:"varint,8,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoRaWANBridge_Uplink) Reset() {
	*x = LoRaWANBridge_Uplink{}
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoRaWANBridge_Uplink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoRaWANBridge_Uplink) ProtoMessage() {}

func (x *LoRaWANBridge_Uplink) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoRaWANBridge_Uplink.ProtoReflect.Descriptor instead.
func (*LoRaWANBridge_Uplink) Descriptor() ([]byte, []int) {
	return file_meshtastic_lorawan_bridge_proto_rawDescGZIP(), []int{0, 0}
}

func (x *LoRaWANBridge_Uplink) GetFreqHz() uint32 {
	if x != nil {
		return x.FreqHz
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetTmst() uint32 {
	if x != nil {
		return x.Tmst
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetRssiX10() int32 {
	if x != nil {
		return x.RssiX10
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetSnrX10() int32 {
	if x != nil {
		return x.SnrX10
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetRadioParams() uint32 {
	if x != nil {
		return x.RadioParams
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetFskBitrate() uint32 {
	if x != nil {
		return x.FskBitrate
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LoRaWANBridge_Uplink) GetPayloadId() uint32 {
	if x != nil {
		return x.PayloadId
	}
	return 0
}

func (x *LoRaWANBridge_Uplink) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

// A downlink from the network server, travelling towards the gateway.
type LoRaWANBridge_Downlink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transmit frequency in Hz.
	FreqHz uint32 `protobuf:"fixed32,1,opt,name=freq_hz,json=freqHz,proto3" json:"freq_hz,omitempty"`
	// Concentrator timestamp to transmit at. Ignored when immediate is set.
	Tmst uint32 `protobuf:"fixed32,2,opt,name=tmst,proto3" json:"tmst,omitempty"`
	// Packed radio settings, encoded as in Uplink.radio_params. FSK downlink is
	// not supported, so there is no bit rate or frequency deviation here.
	RadioParams uint32 `protobuf:"varint,3,opt,name=radio_params,json=radioParams,proto3" json:"radio_params,omitempty"`
	// Transmit power in dBm, 0 to 255. The gateway clamps it to its region.
	PowerDbm uint32 `protobuf:"varint,4,opt,name=power_dbm,json=powerDbm,proto3" json:"power_dbm,omitempty"`
	// Transmit as soon as possible instead of at tmst. Used for Class C.
	Immediate bool `protobuf:"varint,5,opt,name=immediate,proto3" json:"immediate,omitempty"`
	// Invert LoRa polarity. True for every LoRaWAN downlink.
	InvertPolarity bool `protobuf:"varint,6,opt,name=invert_polarity,json=invertPolarity,proto3" json:"invert_polarity,omitempty"`
	// Disable the physical layer CRC.
	NoCrc bool `protobuf:"varint,7,opt,name=no_crc,json=noCrc,proto3" json:"no_crc,omitempty"`
	// Allow the gateway to send this in a later receive window if it arrives too
	// late. Leave clear for anything tied to a specific uplink.
	MayDefer bool `protobuf:"varint,8,opt,name=may_defer,json=mayDefer,proto3" json:"may_defer,omitempty"`
	// Identifies this downlink so its TxResult can be matched to it. 1 to 255.
	RequestId uint32 `protobuf:"varint,12,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// PHY payload, or its first part when chunk_count is 2.
	Payload []byte `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	// Groups this head with its continuation. 1 to 255, or 0 when not chunked.
	PayloadId uint32 `protobuf:"varint,10,opt,name=payload_id,json=payloadId,proto3" json:"payload_id,omitempty"`
	// 0 when the frame fits one packet, otherwise 2.
	ChunkCount    uint32 `protobuf:"varint,11,opt,name=chunk_count,json=chunkCount,proto3" json:"chunk_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoRaWANBridge_Downlink) Reset() {
	*x = LoRaWANBridge_Downlink{}
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoRaWANBridge_Downlink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoRaWANBridge_Downlink) ProtoMessage() {}

func (x *LoRaWANBridge_Downlink) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoRaWANBridge_Downlink.ProtoReflect.Descriptor instead.
func (*LoRaWANBridge_Downlink) Descriptor() ([]byte, []int) {
	return file_meshtastic_lorawan_bridge_proto_rawDescGZIP(), []int{0, 1}
}

func (x *LoRaWANBridge_Downlink) GetFreqHz() uint32 {
	if x != nil {
		return x.FreqHz
	}
	return 0
}

func (x *LoRaWANBridge_Downlink) GetTmst() uint32 {
	if x != nil {
		return x.Tmst
	}
	return 0
}

func (x *LoRaWANBridge_Downlink) GetRadioParams() uint32 {
	if x != nil {
		return x.RadioParams
	}
	return 0
}

func (x *LoRaWANBridge_Downlink) GetPowerDbm() uint32 {
	if x != nil {
		return x.PowerDbm
	}
	return 0
}

func (x *LoRaWANBridge_Downlink) GetImmediate() bool {
	if x != nil {
		return x.Immediate
	}
	return false
}

func (x *LoRaWANBridge_Downlink) GetInvertPolarity() bool {
	if x != nil {
		return x.InvertPolarity
	}
	return false
}

func (x *LoRaWANBridge_Downlink) GetNoCrc() bool {
	if x != nil {
		return x.NoCrc
	}
	return false
}

func (x *LoRaWANBridge_Downlink) GetMayDefer() bool {
	if x != nil {
		return x.MayDefer
	}
	return false
}

func (x *LoRaWANBridge_Downlink) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *LoRaWANBridge_Downlink) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LoRaWANBridge_Downlink) GetPayloadId() uint32 {
	if x != nil {
		return x.PayloadId
	}
	return 0
}

func (x *LoRaWANBridge_Downlink) GetChunkCount() uint32 {
	if x != nil {
		return x.ChunkCount
	}
	return 0
}

// The remainder of a chunked Uplink or Downlink. Carries no RF metadata.
type LoRaWANBridge_PayloadChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches payload_id in the head message. Reassembly keys on the sending
	// node and this value.
	PayloadId uint32 `protobuf:"varint,1,opt,name=payload_id,json=payloadId,proto3" json:"payload_id,omitempty"`
	// Position of this chunk. Always 1.
	ChunkIndex uint32 `protobuf:"varint,2,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	// This part of the PHY payload.
	PayloadChunk  []byte `protobuf:"bytes,3,opt,name=payload_chunk,json=payloadChunk,proto3" json:"payload_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoRaWANBridge_PayloadChunk) Reset() {
	*x = LoRaWANBridge_PayloadChunk{}
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoRaWANBridge_PayloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoRaWANBridge_PayloadChunk) ProtoMessage() {}

func (x *LoRaWANBridge_PayloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoRaWANBridge_PayloadChunk.ProtoReflect.Descriptor instead.
func (*LoRaWANBridge_PayloadChunk) Descriptor() ([]byte, []int) {
	return file_meshtastic_lorawan_bridge_proto_rawDescGZIP(), []int{0, 2}
}

func (x *LoRaWANBridge_PayloadChunk) GetPayloadId() uint32 {
	if x != nil {
		return x.PayloadId
	}
	return 0
}

func (x *LoRaWANBridge_PayloadChunk) GetChunkIndex() uint32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *LoRaWANBridge_PayloadChunk) GetPayloadChunk() []byte {
	if x != nil {
		return x.PayloadChunk
	}
	return nil
}

// The outcome of a downlink, reported back towards the network server.
type LoRaWANBridge_TxResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tmst the downlink was scheduled for. Zero when it was immediate, so
	// diagnostic only; correlate on request_id.
	Tmst uint32 `protobuf:"fixed32,1,opt,name=tmst,proto3" json:"tmst,omitempty"`
	// What happened to it.
	Status LoRaWANBridge_TxResult_Status `protobuf:"varint,2,opt,name=status,proto3,enum=meshtastic.LoRaWANBridge_TxResult_Status" json:"status,omitempty"`
	// Echoes Downlink.request_id.
	RequestId     uint32 `protobuf:"varint,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoRaWANBridge_TxResult) Reset() {
	*x = LoRaWANBridge_TxResult{}
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoRaWANBridge_TxResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoRaWANBridge_TxResult) ProtoMessage() {}

func (x *LoRaWANBridge_TxResult) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_lorawan_bridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoRaWANBridge_TxResult.ProtoReflect.Descriptor instead.
func (*LoRaWANBridge_TxResult) Descriptor() ([]byte, []int) {
	return file_meshtastic_lorawan_bridge_proto_rawDescGZIP(), []int{0, 3}
}

func (x *LoRaWANBridge_TxResult) GetTmst() uint32 {
	if x != nil {
		return x.Tmst
	}
	return 0
}

func (x *LoRaWANBridge_TxResult) GetStatus() LoRaWANBridge_TxResult_Status {
	if x != nil {
		return x.Status
	}
	return LoRaWANBridge_TxResult_NONE
}

func (x *LoRaWANBridge_TxResult) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

var File_meshtastic_lorawan_bridge_proto protoreflect.FileDescriptor

const file_meshtastic_lorawan_bridge_proto_rawDesc = "" +
	"\n" +
	"\x1fmeshtastic/lorawan_bridge.proto\x12\n" +
	"meshtastic\"\xb1\n" +
	"\n" +
	"\rLoRaWANBridge\x12:\n" +
	"\x06uplink\x18\x01 \x01(\v2 .meshtastic.LoRaWANBridge.UplinkH\x00R\x06uplink\x12@\n" +
	"\bdownlink\x18\x02 \x01(\v2\".meshtastic.LoRaWANBridge.DownlinkH\x00R\bdownlink\x12A\n" +
	"\ttx_result\x18\x03 \x01(\v2\".meshtastic.LoRaWANBridge.TxResultH\x00R\btxResult\x12>\n" +
	"\x05chunk\x18\x04 \x01(\v2&.meshtastic.LoRaWANBridge.PayloadChunkH\x00R\x05chunk\x1a\x87\x02\n" +
	"\x06Uplink\x12\x17\n" +
	"\afreq_hz\x18\x01 \x01(\aR\x06freqHz\x12\x12\n" +
	"\x04tmst\x18\x02 \x01(\aR\x04tmst\x12\x19\n" +
	"\brssi_x10\x18\x03 \x01(\x11R\arssiX10\x12\x17\n" +
	"\asnr_x10\x18\x04 \x01(\x11R\x06snrX10\x12!\n" +
	"\fradio_params\x18\x05 \x01(\rR\vradioParams\x12\x1f\n" +
	"\vfsk_bitrate\x18\t \x01(\rR\n" +
	"fskBitrate\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"payload_id\x18\a \x01(\rR\tpayloadId\x12\x1f\n" +
	"\vchunk_count\x18\b \x01(\rR\n" +
	"chunkCount\x1a\xeb\x02\n" +
	"\bDownlink\x12\x17\n" +
	"\afreq_hz\x18\x01 \x01(\aR\x06freqHz\x12\x12\n" +
	"\x04tmst\x18\x02 \x01(\aR\x04tmst\x12!\n" +
	"\fradio_params\x18\x03 \x01(\rR\vradioParams\x12\x1b\n" +
	"\tpower_dbm\x18\x04 \x01(\rR\bpowerDbm\x12\x1c\n" +
	"\timmediate\x18\x05 \x01(\bR\timmediate\x12'\n" +
	"\x0finvert_polarity\x18\x06 \x01(\bR\x0einvertPolarity\x12\x15\n" +
	"\x06no_crc\x18\a \x01(\bR\x05noCrc\x12\x1b\n" +
	"\tmay_defer\x18\b \x01(\bR\bmayDefer\x12\x1d\n" +
	"\n" +
	"request_id\x18\f \x01(\rR\trequestId\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"payload_id\x18\n" +
	" \x01(\rR\tpayloadId\x12\x1f\n" +
	"\vchunk_count\x18\v \x01(\rR\n" +
	"chunkCount\x1as\n" +
	"\fPayloadChunk\x12\x1d\n" +
	"\n" +
	"payload_id\x18\x01 \x01(\rR\tpayloadId\x12\x1f\n" +
	"\vchunk_index\x18\x02 \x01(\rR\n" +
	"chunkIndex\x12#\n" +
	"\rpayload_chunk\x18\x03 \x01(\fR\fpayloadChunk\x1a\xa6\x02\n" +
	"\bTxResult\x12\x12\n" +
	"\x04tmst\x18\x01 \x01(\aR\x04tmst\x12A\n" +
	"\x06status\x18\x02 \x01(\x0e2).meshtastic.LoRaWANBridge.TxResult.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\rR\trequestId\"\xa3\x01\n" +
	"\x06Status\x12\b\n" +
	"\x04NONE\x10\x00\x12\f\n" +
	"\bTOO_LATE\x10\x01\x12\r\n" +
	"\tTOO_EARLY\x10\x02\x12\x14\n" +
	"\x10COLLISION_PACKET\x10\x03\x12\x14\n" +
	"\x10COLLISION_BEACON\x10\x04\x12\v\n" +
	"\aTX_FREQ\x10\x05\x12\f\n" +
	"\bTX_POWER\x10\x06\x12\x10\n" +
	"\fGPS_UNLOCKED\x10\a\x12\f\n" +
	"\bDEFERRED\x10\b\x12\v\n" +
	"\aDROPPED\x10\tB\t\n" +
	"\avariantBj\n" +
	"\x14org.meshtastic.protoB\x13LoRaWANBridgeProtosZ#github.com/meshtastic/go/meshtastic\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00b\x06proto3"

var (
	file_meshtastic_lorawan_bridge_proto_rawDescOnce sync.Once
	file_meshtastic_lorawan_bridge_proto_rawDescData []byte
)

func file_meshtastic_lorawan_bridge_proto_rawDescGZIP() []byte {
	file_meshtastic_lorawan_bridge_proto_rawDescOnce.Do(func() {
		file_meshtastic_lorawan_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtastic_lorawan_bridge_proto_rawDesc), len(file_meshtastic_lorawan_bridge_proto_rawDesc)))
	})
	return file_meshtastic_lorawan_bridge_proto_rawDescData
}

var file_meshtastic_lorawan_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_meshtastic_lorawan_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_meshtastic_lorawan_bridge_proto_goTypes = []any{
	(LoRaWANBridge_TxResult_Status)(0), // 0: meshtastic.LoRaWANBridge.TxResult.Status
	(*LoRaWANBridge)(nil),              // 1: meshtastic.LoRaWANBridge
	(*LoRaWANBridge_Uplink)(nil),       // 2: meshtastic.LoRaWANBridge.Uplink
	(*LoRaWANBridge_Downlink)(nil),     // 3: meshtastic.LoRaWANBridge.Downlink
	(*LoRaWANBridge_PayloadChunk)(nil), // 4: meshtastic.LoRaWANBridge.PayloadChunk
	(*LoRaWANBridge_TxResult)(nil),     // 5: meshtastic.LoRaWANBridge.TxResult
}
var file_meshtastic_lorawan_bridge_proto_depIdxs = []int32{
	2, // 0: meshtastic.LoRaWANBridge.uplink:type_name -> meshtastic.LoRaWANBridge.Uplink
	3, // 1: meshtastic.LoRaWANBridge.downlink:type_name -> meshtastic.LoRaWANBridge.Downlink
	5, // 2: meshtastic.LoRaWANBridge.tx_result:type_name -> meshtastic.LoRaWANBridge.TxResult
	4, // 3: meshtastic.LoRaWANBridge.chunk:type_name -> meshtastic.LoRaWANBridge.PayloadChunk
	0, // 4: meshtastic.LoRaWANBridge.TxResult.status:type_name -> meshtastic.LoRaWANBridge.TxResult.Status
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_meshtastic_lorawan_bridge_proto_init() }
func file_meshtastic_lorawan_bridge_proto_init() {
	if File_meshtastic_lorawan_bridge_proto != nil {
		return
	}
	file_meshtastic_lorawan_bridge_proto_msgTypes[0].OneofWrappers = []any{
		(*LoRaWANBridge_Uplink_)(nil),
		(*LoRaWANBridge_Downlink_)(nil),
		(*LoRaWANBridge_TxResult_)(nil),
		(*LoRaWANBridge_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtastic_lorawan_bridge_proto_rawDesc), len(file_meshtastic_lorawan_bridge_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtastic_lorawan_bridge_proto_goTypes,
		DependencyIndexes: file_meshtastic_lorawan_bridge_proto_depIdxs,
		EnumInfos:         file_meshtastic_lorawan_bridge_proto_enumTypes,
		MessageInfos:      file_meshtastic_lorawan_bridge_proto_msgTypes,
	}.Build()
	File_meshtastic_lorawan_bridge_proto = out.File
	file_meshtastic_lorawan_bridge_proto_goTypes = nil
	file_meshtastic_lorawan_bridge_proto_depIdxs = nil
}
