// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: meshtastic/mesh_beacon.proto

package meshtastic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payload for MESH_BEACON_APP packets.
// Periodically broadcast by nodes in beacon mode.
// Listeners deliver the text message to the local inbox and cache any offered
// channel/preset for the client app to act on — the firmware never auto-applies them.
type MeshBeacon struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable beacon message. Max 100 bytes enforced by firmware on send.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Optional channel (name + PSK) being advertised to listening clients.
	// A client app may offer to switch the user to this channel; firmware never applies it automatically.
	OfferChannel *ChannelSettings `protobuf:"bytes,2,opt,name=offer_channel,json=offerChannel,proto3" json:"offer_channel,omitempty"`
	// Optional region being advertised alongside offer_preset.
	OfferRegion Config_LoRaConfig_RegionCode `protobuf:"varint,3,opt,name=offer_region,json=offerRegion,proto3,enum=meshtastic.Config_LoRaConfig_RegionCode" json:"offer_region,omitempty"`
	// Optional modem preset being advertised.
	// Combined with offer_region, tells a client "there is a mesh on this preset/region".
	OfferPreset   *Config_LoRaConfig_ModemPreset `protobuf:"varint,4,opt,name=offer_preset,json=offerPreset,proto3,enum=meshtastic.Config_LoRaConfig_ModemPreset,oneof" json:"offer_preset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeshBeacon) Reset() {
	*x = MeshBeacon{}
	mi := &file_meshtastic_mesh_beacon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeshBeacon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeshBeacon) ProtoMessage() {}

func (x *MeshBeacon) ProtoReflect() protoreflect.Message {
	mi := &file_meshtastic_mesh_beacon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeshBeacon.ProtoReflect.Descriptor instead.
func (*MeshBeacon) Descriptor() ([]byte, []int) {
	return file_meshtastic_mesh_beacon_proto_rawDescGZIP(), []int{0}
}

func (x *MeshBeacon) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MeshBeacon) GetOfferChannel() *ChannelSettings {
	if x != nil {
		return x.OfferChannel
	}
	return nil
}

func (x *MeshBeacon) GetOfferRegion() Config_LoRaConfig_RegionCode {
	if x != nil {
		return x.OfferRegion
	}
	return Config_LoRaConfig_UNSET
}

func (x *MeshBeacon) GetOfferPreset() Config_LoRaConfig_ModemPreset {
	if x != nil && x.OfferPreset != nil {
		return *x.OfferPreset
	}
	return Config_LoRaConfig_LONG_FAST
}

var File_meshtastic_mesh_beacon_proto protoreflect.FileDescriptor

const file_meshtastic_mesh_beacon_proto_rawDesc = "" +
	"\n" +
	"\x1cmeshtastic/mesh_beacon.proto\x12\n" +
	"meshtastic\x1a\x18meshtastic/channel.proto\x1a\x17meshtastic/config.proto\"\x99\x02\n" +
	"\n" +
	"MeshBeacon\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12@\n" +
	"\roffer_channel\x18\x02 \x01(\v2\x1b.meshtastic.ChannelSettingsR\fofferChannel\x12K\n" +
	"\foffer_region\x18\x03 \x01(\x0e2(.meshtastic.Config.LoRaConfig.RegionCodeR\vofferRegion\x12Q\n" +
	"\foffer_preset\x18\x04 \x01(\x0e2).meshtastic.Config.LoRaConfig.ModemPresetH\x00R\vofferPreset\x88\x01\x01B\x0f\n" +
	"\r_offer_presetBg\n" +
	"\x14org.meshtastic.protoB\x10MeshBeaconProtosZ#github.com/meshtastic/go/meshtastic\xaa\x02\x14Meshtastic.Protobufs\xba\x02\x00b\x06proto3"

var (
	file_meshtastic_mesh_beacon_proto_rawDescOnce sync.Once
	file_meshtastic_mesh_beacon_proto_rawDescData []byte
)

func file_meshtastic_mesh_beacon_proto_rawDescGZIP() []byte {
	file_meshtastic_mesh_beacon_proto_rawDescOnce.Do(func() {
		file_meshtastic_mesh_beacon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshtastic_mesh_beacon_proto_rawDesc), len(file_meshtastic_mesh_beacon_proto_rawDesc)))
	})
	return file_meshtastic_mesh_beacon_proto_rawDescData
}

var file_meshtastic_mesh_beacon_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_meshtastic_mesh_beacon_proto_goTypes = []any{
	(*MeshBeacon)(nil),                 // 0: meshtastic.MeshBeacon
	(*ChannelSettings)(nil),            // 1: meshtastic.ChannelSettings
	(Config_LoRaConfig_RegionCode)(0),  // 2: meshtastic.Config.LoRaConfig.RegionCode
	(Config_LoRaConfig_ModemPreset)(0), // 3: meshtastic.Config.LoRaConfig.ModemPreset
}
var file_meshtastic_mesh_beacon_proto_depIdxs = []int32{
	1, // 0: meshtastic.MeshBeacon.offer_channel:type_name -> meshtastic.ChannelSettings
	2, // 1: meshtastic.MeshBeacon.offer_region:type_name -> meshtastic.Config.LoRaConfig.RegionCode
	3, // 2: meshtastic.MeshBeacon.offer_preset:type_name -> meshtastic.Config.LoRaConfig.ModemPreset
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_meshtastic_mesh_beacon_proto_init() }
func file_meshtastic_mesh_beacon_proto_init() {
	if File_meshtastic_mesh_beacon_proto != nil {
		return
	}
	file_meshtastic_channel_proto_init()
	file_meshtastic_config_proto_init()
	file_meshtastic_mesh_beacon_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshtastic_mesh_beacon_proto_rawDesc), len(file_meshtastic_mesh_beacon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshtastic_mesh_beacon_proto_goTypes,
		DependencyIndexes: file_meshtastic_mesh_beacon_proto_depIdxs,
		MessageInfos:      file_meshtastic_mesh_beacon_proto_msgTypes,
	}.Build()
	File_meshtastic_mesh_beacon_proto = out.File
	file_meshtastic_mesh_beacon_proto_goTypes = nil
	file_meshtastic_mesh_beacon_proto_depIdxs = nil
}
